name: 🐳 Docker Images CI/CD

on:
  push:
    branches:
      - main
      - dev
  release:
    types: [published]

jobs:
  build-and-push:
    name: Docker Build and Push
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            dockerfile: Dockerfile.linux
            platform: linux
          - os: windows-latest
            dockerfile: Dockerfile.windows
            platform: windows
    runs-on: ${{ matrix.os }}

    steps:
      - name: 🔍 Checkout Repository
        uses: actions/checkout@v4

      - name: 🖥️ Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # 🏷️ Fetch Commit SHA
      - name: 🏷️ Fetch Commit SHA
        run: echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # 🏷️ Setup Environment Variables for Branch Name or Tag
      - name: 🏷️ Extract Branch Name or Tag
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "VERSION=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "release" ]]; then
            echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          fi
        shell: bash

      - name: 🛠️ Setup QEMU (Linux Only)
        if: matrix.platform == 'linux'
        uses: docker/setup-qemu-action@v3

      - name: 🛠️ Setup Docker Buildx (Linux Only)
        if: matrix.platform == 'linux'
        uses: docker/setup-buildx-action@v3

      # 🛠️ Build and Push Docker Images
      - name: 🛠️ Build and Push Docker Images
        run: |
          # Build the Docker image with the primary tag (branch or tag name).
          docker build -t dublok/statsniper:${{ matrix.platform }}-${{ env.VERSION }} -f ./src/${{ matrix.dockerfile }} ./src
          
          # Tag the built image with the commit SHA.
          docker tag dublok/statsniper:${{ matrix.platform }}-${{ env.VERSION }} dublok/statsniper:${{ matrix.platform }}-${{ env.VERSION }}-${{ env.SHA }}
          
          # Push the primary tag and SHA tag in all cases.
          docker push dublok/statsniper:${{ matrix.platform }}-${{ env.VERSION }}
          docker push dublok/statsniper:${{ matrix.platform }}-${{ env.VERSION }}-${{ env.SHA }}
          
          # For releases, also tag as 'latest' and push this tag.
          if [[ "${{ github.event_name }}" == "release" ]]; then
            docker tag dublok/statsniper:${{ matrix.platform }}-${{ env.VERSION }} dublok/statsniper:${{ matrix.platform }}-latest
            docker push dublok/statsniper:${{ matrix.platform }}-latest
          fi
        shell: bash
